version: '3'
services:
  #services

  gateway:
    image: traefik:v1.7
    command: --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  files:
    container_name: files
    build: ./picart-files-service
    environment:
      - MONGODB_URL=mongodb://mongo:27017/files
      - PORT=3000
      - TOKEN_SECRET=secret
    depends_on:
      - mongo

  images:
    container_name: images
    build: ./picart-images-service
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongo:27017/images
    depends_on:
      - mongo

  profiles:
    container_name: profiles
    build: ./picart-profiles-service
    environment:
      - MONGODB_URL=mongodb://mongo:27017/profiles
      - PORT=3000
      - TOKEN_SECRET=secret
      - ADMIN_PASSWORD=test
      - SENDER_EMAIL
      - SENDER_EMAIL_PASSWORD
    depends_on:
      - mongo
    labels:
      - "traefik.backend=profiles"
      - "traefik.frontend.rule=PathPrefix:/api/v1/profiles,/api/v1/tokens;ReplacePathRegex:^/api/v1/(.*) /$$1"
      - "traefik.port=3000"
      - "traefik.backend.healthcheck.path=/service/health"

  #databases
    
  mongo:
    image: 'mongo'
    volumes:
      - mongo:/data/db

volumes:
  mongo: {}
